### ISSUE TITLE
Please add descriptive topics

### ISSUE THREAD

**Issue by leebrian** [CDCgov/MIRA-NF#38]
### Description of the bug

To help people find and use your project, would you please add some topics/keywords (per the CDC open practices guide, https://github.com/CDCgov/template/blob/main/open_practices.md#required-practices).

Since you're in ID, please add at least `cdc-influenza-division` and `ncird-id` (per the ID SOP https://flu-informatics.pages.biotech.cdc.gov/idkb/docs/policy_sop/open_source_sop.html [intranet only]).

I noticed this when I was looking up some stats for a report out. I'm adding this issue to all our repos that don't have it, but if I forget one, please go ahead and update any you know about.

**Comment by kristinelacek** [comment]
[quality-control](https://github.com/topics/quality-control) [nextflow](https://github.com/topics/nextflow) [genome-annotation](https://github.com/topics/genome-annotation) [irma](https://github.com/topics/irma) [influenza](https://github.com/topics/influenza) [genome-assembly](https://github.com/topics/genome-assembly) [nf-core](https://github.com/topics/nf-core) [nextflow-pipeline](https://github.com/topics/nextflow-pipeline) [sars-cov-2](https://github.com/topics/sars-cov-2) [rsv](https://github.com/topics/rsv) [ncird-id](https://github.com/topics/ncird-id) [cdc-influenza-division](https://github.com/topics/cdc-influenza-division)
